### ISSUE TITLE
Failing for very large numbers?

### ISSUE THREAD

**Issue by snakecult** [jiecao-fm/hashids-java#11]
When running some random data through Hashids I found this failure:

```
@Test
public void test_issue11() throws Exception
{
    final Hashids hashIds = new Hashids("Fd2s3lDF1l39PDybtiZI", 5);
    final long id = 3945448269169105809L;
    assertThat(id, equalTo(hashIds.decrypt(hashIds.encrypt(id))[0]));
}
```

java.lang.AssertionError: 
Expected: 3945448269169105408L
     but: was 3945448269169105809L

**Comment by rparvathaneni** [comment]
I just tried rerunning the above test using `Long.MAX_VALUE` as input and the test seem to pass no problem. Any other particular reason to limit the MAX_NUMBER to `9_007_199_254_740_992L`?

``` 
@Test
    public void test_issue11() throws Exception
    {
        final Hashids hashIds = new Hashids("Fd2s3lDF1l39PDybtiZI", 5);
        final long id = Long.MAX_VALUE;
        System.out.println(id);
        assertEquals(id, hashIds.decode(hashIds.encode(id))[0]);
    }
```

**Comment by 0x3333** [comment]
The reason is interop, the javascript version is limited(At least, it was) to `9_007_199_254_740_992L`.
