### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by ui4j** [jiecao-fm/hashids-java#18]
Could you please document the javadoc if Hashids class is thread safe or not?

Thanks

**Comment by fanweixiao** [comment]
@ui4j Can you send a PR about this :yum:

**Comment by eskatos** [comment]
@fanweixiao do you happen to know if it is thread safe or not ?

**Comment by rauanmaemirov** [comment]
I tried to use the tool in multi-thread environment generating ~400k hashes from unique set of numbers and after about 100k generated hashes something breaks. I couldn't find the issue so I gave up and chose different path.

**Comment by ui4j** [comment]
Hi @rauanmaemirov Could you please share your alternative solution.

**Comment by rauanmaemirov** [comment]
@ui4j That depends on what is your case. My task required to simply generate some unique string id, so I ended up using hex of current timestamp in millis.

You probably might try wrapping your encoding code in `synchronized` block.

**Comment by ui4j** [comment]
Thanks for the suggestion. I found [alternative](https://github.com/werval/werval/blob/master/io.werval/io.werval.api/src/main/java/io/werval/util/Hashids.java) implementation for the Hashids api. But i am not sure if its [thread safe](https://github.com/werval/werval/issues/260) or not.

**Comment by 0x3333** [comment]
@rauanmaemirov do you still have this test case?
