### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by nmickuli** [jiecao-fm/hashids-java#22]
I ran a quick stress test on this library and I'm seeing very poor and unpredictable performance. Generating 1,000,000 ids from the same Hashids instance (same salt) takes anywhere between 15 and 90 seconds on a 2.9GHz i7 CPU using 1.8 GB of RAM. There's also a strange stall somewhere between 30k and 60k in the test loop, after which the rest of the test runs quickly.

Here's my test case:

```
    // generates a random 32 character string
    Hashids h = new Hashids(RandomStringUtils.random(32));
    long start = System.currentTimeMillis();
    for (int i = 0; i < 1000000; i++) {
      h.encode(i);
    }
    long end = System.currentTimeMillis();
    long duration = end - start;
    System.out.println("time taken: " + duration/1000 + " seconds");
    System.out.println("hashes per second: " + 1000000/(duration/1000.0));
```

**Comment by Bessonov** [comment]
>10000 hashes in a second in the worst case - wow! It has excellent performance!

But, unfortunately, your benchmark says nothing about performance. Microbenchmarking is hard, partially on modern processors with HT, multilevel caches, JIT compiler, concurrent GC and so on...

**Comment by shane-axiom** [comment]
FWIW this test produces stable results for me on a 2.67GHz proc (Intel Xeon W3520):

    time taken: 18 seconds
    hashes per second: 53949.07207596029

**Comment by nmickuli** [comment]
This wasn't intended to be a benchmark. I'm not comparing the performance of this code to anything else.

I was simply trying to point out that, at least on my machine, there were large variations in the time required to complete the above test, and that the test had strange behavior (like the stalls that I mentioned). I wouldn't expect that, given that this code is simply generating hashes.

Hey, it could just be my machine, and if so then that's great, go ahead and ignore this. I thought the issue at least warranted an investigation to see whether others could reproduce the same behavior.

Ultimately I'm just trying to help improve the code by sharing my findings, if there is any room for improvement here.

**Comment by 0x3333** [comment]
Hi @nmickuli

I know this is an old issue, but is like to address it.

About your issue,  as @Bessonov said, this kind of benchmark is complicated. 

I changed a bit your code to include a warmup phase, added `-XX:+PrintCompilation, -verbose:gc` so we know if JVM is doing any work in between, also I used the same salt every time. Different salts may be faster than others.

In my tests I got very consistent results. 

When I got to my machine I'll share my code and results. 

If you still see those stalls let me know.

**Comment by 0x3333** [comment]
As long as I could check, results got pretty similar.

```
time taken: 10 seconds
hashes per second: 95987.7135726627
time taken: 10 seconds
hashes per second: 97314.1300116777
time taken: 10 seconds
hashes per second: 99265.43577526306
time taken: 10 seconds
hashes per second: 99453.00845350572
time taken: 10 seconds
hashes per second: 98658.24782951856
```

Number of hashes per second is kind of increasing as the JVM get hot.

I'll close this. If new data is available, fell free to open it again.

Thanks.
