### ISSUE TITLE
Non compatible output when alphabet has no O and no 0

### ISSUE THREAD

**Issue by sirotopr** [jiecao-fm/hashids-java#23]
Both this Java implementation and @newhoggy's [hashids-scala](https://github.com/newhoggy/hashids-scala) output a wrong value while using the following alphabet: `ABCDEFGHIJKLMNPQRSTUVWXYZ123456789`. It's comprised of all capital case letters except `O` plus all digits except `0`. Adding either `O` or `0` makes it work again. Something is wrong in your code when both are missing.

Here are my test results:

##### JavaScript (reference) implementation: [hashids.js](https://github.com/ivanakimov/hashids.js) 1.0.2
```javascript
var hashids = new Hashids("MyCamelCaseSalt", 10, "ABCDEFGHIJKLMNPQRSTUVWXYZ123456789");
console.log(hashids.encode(1145));
```
`9Q7MJ3LVGW`

##### Python implementation: [hashids-python](https://github.com/davidaurelio/hashids-python) 1.1.0.egg-info (from pip repos)
```python
import sys, getopt
from hashids import Hashids

hashids = Hashids(salt="MyCamelCaseSalt", min_length=10, alphabet="ABCDEFGHIJKLMNPQRSTUVWXYZ123456789")
print hashids.encode(1145)
```
`9Q7MJ3LVGW`

##### Java implementation: [hashids-java](https://github.com/jiecao-fm/hashids-java) 1.0.1 (from Maven Central)
```java
import org.hashids.*;

public class Test {
    public static void main(String[] args) {
		Hashids hashids = new Hashids("MyCamelCaseSalt", 10, "ABCDEFGHIJKLMNPQRSTUVWXYZ123456789");
		System.out.println(hashids.encode(1145));
    }
}
```
`9E85K9Q623`

##### Scala implementation: [hashids-scala](https://github.com/newhoggy/hashids-scala) 1.1.0-448df98 (from io.john-ky)
```scala
import org.hashids._

object Test extends App {
  val hashids = Hashids("MyCamelCaseSalt", 10, "ABCDEFGHIJKLMNPQRSTUVWXYZ123456789")
  println(hashids.encode(1145))
}
```
`9E85K9Q623`

**Comment by newhoggy** [comment]
Hi @sirotopr,

I've done some preliminary investigations and have determined that the underlying encode and decode methods are good.  It is just a matter of initialisation of the `Hashid` object not working properly.

I haven't yet worked out why the initialisation isn't working, but if you desire, there is an new Scala library version that exposes the internal state as a `HashidImpl` case class.  With this a possible work around is to use the Python code to generate the internal state for you and initialise that state into `HashidImpl` and you should get the correct encode/decode behaviour:

    libraryDependencies += "io.john-ky" %% "hashids-scala" % "1.1.0-b33fd4e"
