### ISSUE TITLE
hashids not support number > 9007199254740992L

### ISSUE THREAD

**Issue by bichtv** [jiecao-fm/hashids-java#35]
hashids not support number > 9007199254740992L. can you update source to support number > 9007199254740992L ?

**Comment by 0x3333** [comment]
This is a limitation of the algorithm. All hashids have it. We can't do it.

**Comment by arcticicestudio** [comment]
This limit provides more than 9 quadrillion (!) possible numbers. I think even YouTube hasn't reached this amount of video ID's if they'd use this algorithm.
Maybe you should describe what's your actual problem with this limit. There are workarounds to get above this limit like for example using a array with multiple `long` numbers which can be multiplied when they get decoded.

**Comment by bichtv** [comment]
thanks for the help, I have solved my problem with hashid

**Comment by fanweixiao** [comment]
congratulations @bichtv , and, it's hashids :smile:
