### ISSUE TITLE
Specifying custom hash alphabet

### ISSUE THREAD

**Issue by gikarasojo** [jiecao-fm/hashids-java#36]
I have extracted the below extract  from [your main page](https://github.com/jiecao-fm/hashids-java#specifying-custom-hash-alphabet)

> Here we set the alphabet to consist of only four letters: "0123456789abcdef"
`Hashids hashids = new Hashids("this is my salt", 0, "0123456789abcdef");
String hash = hashids.encode(1234567L);`

> hash is now going to be:
`b332db5`

**the alphabet consists of 6 letters! a,b,c,d,e,f**

**Comment by fanweixiao** [comment]
any problem? the algorithm designed as you only need [0-9] and [a-f] chars?

**Comment by 0x3333** [comment]
@fanweixiao what @gikarasojo is trying to say is that we state that:
`only four letters`, but actually we have six.

**Comment by fanweixiao** [comment]
@0x3333 @gikarasojo Oh, I see! yep, should be `six`, haha
