### ISSUE TITLE
Question about the output

### ISSUE THREAD

**Issue by ulisses79** [jiecao-fm/hashids-java#42]
Sorry for maybe naive question but....
Assuming that my alpha is complete i.e. contains all characters and digits.
I wonder if there is a possibility that _encode_ method would return a hash which contains only digits?
Other words is there a string which can be encoded and the result contains only digits?
Is it guaranteed that at leat one letter is present in the output?

**Comment by 0x3333** [comment]
No, alphabet must contain at least 16 unique characters, including numbers. This is by design.
There is no guarantee that the output will contains a group of the alphabet characters.

**Comment by ulisses79** [comment]
Thank you for the answer.
