### ISSUE TITLE
Removal of deprecated methods 

### ISSUE THREAD

**Issue by 0x3333** [jiecao-fm/hashids-java#44]
Deprecated methods:

```
public String encrypt(long... numbers)
public long[] decrypt(String hash)
public String encryptHex(String hexa)
public String decryptHex(String hash)
```

have been deprecated since Sep 15, 2014, I think we should remove them in the next release.

@fanweixiao

**Comment by fanweixiao** [comment]
Sorry for the delay response, yes, we should deprecate these.
