### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by 0x3333** [jiecao-fm/hashids-java#45]
From issue [Issue 43 - kmandeville](https://github.com/jiecao-fm/hashids-java/issues/43#issuecomment-307491507):

> I have found two other occurrences where I get ArrayIndexOutOfBoundsException from deep in the HashIds code.
> `Hashids hashids = new Hashids("this is my salt"); long[] numbers = hashids.decode("[]");`
> 
> and
> 
> `Hashids hashids = new Hashids("this is my salt"); long[] numbers = hashids.decode("()");`
> 
> Like the original submitter above, these aren't valid hashes, but I'm running into these errors in my web app because someone COULD put these characters in as an ID in a URL accidentally or on purpose. My app is just passing in these characters directly into HashIds. I would expect something other than ArrayIndexOutOfBoundsExceptions.

**Comment by 0x3333** [comment]
Fixed, instead finding all `charAt` that could throw an ArrayIndexOutOfBoundsException, I validate the decode method input, in case of invalid chars, return an empty array(Default JS implementation behaviour).

**Comment by kmandeville** [comment]
Will there be a new release in the near future? I'd rather not have to use a snapshot version

**Comment by kmandeville** [comment]
I didn't expect there to be one just for this fix. Was just wondering what the current plan was so I could plan on my side accordingly. Thank you!

**Comment by 0x3333** [comment]
No problem! Subscribe to the issue #44 , when it got fixed probably we will have a new release! Thanks for your help!

**Comment by 0x3333** [comment]
Just to inform a new version has been issued! 1.0.3.
