### ISSUE TITLE
base58 alphabet

### ISSUE THREAD

**Issue by vkorobkov** [jiecao-fm/hashids-java#46]
Hi,

What do you think about adding a constant(`public final static string BASE_58 = ...`) with base58(https://en.wikipedia.org/wiki/Base58) alphabet right into `Hashids` class?

Base58 alphabet looks very well to be used in url paths because it excludes many confusions when letters are different but seem similar visually(0 (zero), O (capital o), I (capital i) and l (lower case L) )

If you like this idea, I can prepare small a PR. THanks

**Comment by 0x3333** [comment]
Hi!
I believe that this is out of scope of the project. This can be easily implemented by the end-user. 
Despite that, I believe we could add this info in the README.
Thanks.
