### ISSUE TITLE
 diffrent results in python and java with same alphabet and salt

### ISSUE THREAD

**Issue by syncml** [jiecao-fm/hashids-java#48]
Python(2.7  hashids version=1.0.2):

> from hashids import Hashids
> hashids = Hashids(salt='this is my salt',alphabet='0123456789abcdefghijklmnopqrstuvwx')
> print hashids.encode(654321) # print **gr9gdg**

java (hashids version=1.0.2):

> Hashids hashids = new Hashids("this is my salt", 0, "0123456789abcdefghijklmnopqrstuvwx");
> System.out.println(hashids.encode(654321)); # print **wwp5p6**

if alphabet='0123456789abcdefghijklmnopqrstuvwxyz',  the result is nice.  

It's a bug?

**Comment by 0x3333** [comment]
The correct response is `gr9gdg`, testing using your parameters, I got `gr9gdg` correctly.

How did you get `wwp5p6`?

![screen shot 2017-07-11 at 11 14 52](https://user-images.githubusercontent.com/289289/28072705-3486e43c-662a-11e7-9e2e-28d9a997eee1.png)

**Comment by syncml** [comment]
Sorry. Sorry.Sorry. 

My java app running the test case use the  1.0.1 version rather than 1.0.2 :( ，so it got incorrect response.
1.0.1 response is wwp5p6
1.0.2 response is gr9gdg

**Comment by 0x3333** [comment]
Just to inform a new version has been issued! 1.0.3.
