### ISSUE TITLE
Is there any way to provide maximum hash length

### ISSUE THREAD

**Issue by yogitaAP** [jiecao-fm/hashids-java#50]
The way I can provide a minimum character length for the generated hash. Can I provide a maximum hash length as well? If no, is there any workaround.

**Comment by 0x3333** [comment]
You have 4 constructors:

```java
  public Hashids() {
  }

  public Hashids(String salt) {
  }

  public Hashids(String salt, int minHashLength) {
  }

  public Hashids(String salt, int minHashLength, String alphabet) {
  }
```

A maximum can't be provided.
