### ISSUE TITLE
Publish into Maven Central

### ISSUE THREAD

**Issue by manikantag** [jiecao-fm/hashids-java#8]
Hi, publishing into Maven Central makes it very easy to integrate into build process.

Thanks

**Comment by pawelantczak** [comment]
Bump!

**Comment by rartavia** [comment]
@fanweixiao any progress? Can we have it in jcenter?

**Comment by jitpack** [comment]
Btw, it is easily available from https://jitpack.io/#jiecao-fm/hashids-java/v1.0.0 : )

**Comment by manikantag** [comment]
@jitpack Great! Very nice idea. Thanks.

**Comment by fanweixiao** [comment]
@jitpack :+1:

**Comment by giulp** [comment]
@fanweixiao maybe this could be relevant and useful [rultor](http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html)

**Comment by fanweixiao** [comment]
@rultor hello

**Comment by fanweixiao** [comment]
@rultor release, tag=`1.0.0`

**Comment by fanweixiao** [comment]
@giulp seems it's not easy to use rultor. I am not familiar maven-related things, if you have experience on this, can you help publishing this project to maven central? if sure, I can add you to collaborator so you can use rultor to release it :smile:

**Comment by giulp** [comment]
@fanweixiao it'd be a pleasure and a honour to help :) count me in

**Comment by fanweixiao** [comment]
@giulp I've invited you to a team for collaborating, please accept :)

**Comment by tcollins** [comment]
:+1: for jcenter / maven central

**Comment by Bessonov** [comment]
Now is 1.0.0 released. Any updates on this issue?

**Comment by fanweixiao** [comment]
@giulp how's about the process :8ball:

**Comment by giulp** [comment]
busy giulp's been investigating it

will push an update in a couple of days

**Comment by fanweixiao** [comment]
@giulp :+1:

**Comment by laguiz** [comment]
+1 for maven

**Comment by shane-axiom** [comment]
:clock1: :clock2: :clock3: :clock4: :question:

**Comment by giulp** [comment]
Sorry guys too busy atm maybe someone else wants to take the task

2015-06-02 8:41 GMT+02:00 Shane StClair <notifications@github.com>:

**Comment by shane-axiom** [comment]
Created a [Sonatype JIRA ticket](https://issues.sonatype.org/browse/OSSRH-15882) to try to get this moving.

**Comment by fanweixiao** [comment]
@shane-axiom I've added you to the team, you'll have admin access to this repo :)

**Comment by thwatson** [comment]
I'm about to prepare the repo.  Per the ticket, only Shane will get a deployer role.  If any other team members need deployer roles, just comment on the ticket and I'll add you.

**Comment by shane-axiom** [comment]
Thanks @thwatson. @fanweixiao I notice that the Maven groupId for the project was `fm.jiecao.lib` when v1.0.0 was released, and I set up the OSS repo to use the current groupId `org.hashids`. Can I go ahead and release v1.0.1 and push that?

**Comment by fanweixiao** [comment]
Yes, I will try to remove the old v1.0.0 version, we should use `org.hashids` as groupId. thanks a lot.

**Comment by shane-axiom** [comment]
Alright, v1.0.1 is publushed and available via Maven Central!

**Comment by fanweixiao** [comment]
@shane-axiom :+1: :+1:
